# Generated by Django 4.2.30 on 2026-05-23 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerableIndividual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('photo', models.ImageField(help_text='Recent photograph of the individual.', upload_to='vulnerable_photos/')),
                ('address', models.TextField(help_text='Primary residential address.')),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('medical_notes', models.TextField(blank=True, help_text='Crucial medical conditions, allergies, or instructions.')),
                ('last_known_location', models.TextField(blank=True, help_text='Last known location coordinates or descriptive address.')),
                ('qr_code_image', models.ImageField(blank=True, help_text='Automatically generated QR code for field identification.', null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('missing', 'Missing'), ('found', 'Found')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(help_text='The user/family who registered this individual.', on_delete=django.db.models.deletion.CASCADE, related_name='created_individuals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_image', models.ImageField(help_text='Photo of the found individual or scene.', upload_to='incident_photos/')),
                ('location_found', models.TextField(help_text='Address or description of where they were found.')),
                ('description', models.TextField(help_text="Details about the individual's appearance, behavior, or condition.")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audio_transcript', models.TextField(blank=True, help_text='Optional audio note transcription if a voice report was submitted.', null=True)),
                ('reporter', models.ForeignKey(blank=True, help_text='The citizen reporter. Leave blank for anonymous reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
