# Generated by Django 4.2.30 on 2026-05-23 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_potentialmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude from map picker', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude from map picker', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='potentialmatch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
