# Generated by Django 4.2.30 on 2026-06-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_deletevulnerableindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='report_type',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'Found')], default='missing', help_text='Whether this report is for a missing person or a found person.', max_length=10),
        ),
        migrations.AlterField(
            model_name='vulnerableindividual',
            name='status',
            field=models.CharField(choices=[('Safe', 'Safe'), ('active', 'Active'), ('missing', 'Missing'), ('found', 'Found')], default='Safe', max_length=10),
        ),
    ]
