# Generated by Django 4.2.30 on 2026-06-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_incidentreport_report_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminMatchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.vulnerableindividual')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.incidentreport')),
            ],
            options={
                'unique_together': {('profile', 'report')},
            },
        ),
    ]
