# Generated by Django 4.2.30 on 2026-06-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_geminmatchcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='registry.vulnerableindividual'),
        ),
    ]
