# Generated by Django 4.2.30 on 2026-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_incidentreport_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
