# Generated by Django 4.2.30 on 2026-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_incidentreport_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='finder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='finder_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
