# Generated by Django 4.2.30 on 2026-07-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_incidentreport_finder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerableindividual',
            name='instructions_for_finder',
            field=models.TextField(blank=True, help_text='Instructions for anyone who finds this person.'),
        ),
    ]
