# Generated by Django 4.2.30 on 2026-07-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_vulnerableindividual_instructions_for_finder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='uploaded_image',
            field=models.ImageField(blank=True, help_text='Photo of the found individual or scene.', null=True, upload_to='incident_photos/'),
        ),
    ]
